import Constants from 'expo-constants';
import { Platform } from 'react-native';

// Production URL
const PRODUCTION_URL = 'https://beacon-mhealth-production.up.railway.app/api';

/**
 * Get the API URL based on the environment.
 */
const getApiUrl = () => {
    if (__DEV__) {
        // Automatically determine local machine's IP address generated by Expo Bundler
        const debuggerHost = Constants.expoConfig?.hostUri;
        if (debuggerHost) {
            const localhost = debuggerHost.split(':')[0];
            return `http://${localhost}:3000/api`;
        }
        // Fallback loops for physical vs emulated devices
        return Platform.OS === 'android' ? 'http://10.0.2.2:3000/api' : 'http://localhost:3000/api';
    }
    
    // For Production Mode
    return PRODUCTION_URL;
};

export const API_URL = getApiUrl();
